# Mesh Config: MANET-HR-auto
EUD_CONNECTION="auto"
LAN_AP_SSID="MANET"
LAN_AP_KEY="raspberry"
MAX_EUDS_PER_NODE="20"
INSTALL_MEDIAMTX="y"
INSTALL_MUMBLE="y"
REGULATORY_DOMAIN="HR"
HALOW_REGULATORY_DOMAIN="EU"
MESH_SSID="MESH"
MESH_SAE_KEY="5cAKt6KRrxatlDghiAzeXIZ9jkubLMVUHm0/bchIDgxZooomywHdqabZ3d0D"
LAN_CIDR_BLOCK="10.30.2.0/24"
AUTO_CHANNEL="n"
RADIO_PW="raspberry"
ADMIN_PW="raspberry"
AUTO_UPDATE="n"
